In [2]:
import pandas as pd
data={
    'department':['HR','sales','IT','sales','IT','HR','sales'],
    'employee':['A','B','C','D','E','F','G'],
    'salary':[50000,60000,45000,70000,72000,71000,73000],
    'experience':[2,4,3,5,6,7,5]
}
df=pd.DataFrame(data)
print(df)

  department employee  salary  experience
0         HR        A   50000           2
1      sales        B   60000           4
2         IT        C   45000           3
3      sales        D   70000           5
4         IT        E   72000           6
5         HR        F   71000           7
6      sales        G   73000           5

In [8]:
df3=df.groupby('experience').sum()
print(df3)

            department employee  salary
experience
2                   HR        A   50000
3                   IT        C   45000
4                sales        B   60000
5           salessales       DG  143000
6                   IT        E   72000
7                   HR        F   71000

In [3]:
df.groupby(['department','experience']).sum()

                      employee  salary
department experience
HR         2                 A   50000
           7                 F   71000
IT         3                 C   45000
           6                 E   72000
sales      4                 B   60000
           5                DG  143000

In [12]:
df.groupby(['department','salary']).sum()

                  employee  experience
department salary
HR         50000         A           2
           71000         F           7
IT         45000         C           3
           72000         E           6
sales      60000         B           4
           70000         D           5
           73000         G           5

In [13]:
df.groupby('department')['salary'].sum()

department
HR       121000
IT       117000
sales    203000
Name: salary, dtype: int64

In [15]:
df1=df.groupby(['department','experience']).sum()
print(df1)

                      employee  salary
department experience
HR         2                 A   50000
           7                 F   71000
IT         3                 C   45000
           6                 E   72000
sales      4                 B   60000
           5                DG  143000

In [16]:
df2=df.groupby('department').sum()
print(df2)

           employee  salary  experience
department
HR               AF  121000           9
IT               CE  117000           9
sales           BDG  203000          14

In [19]:
df.groupby('department').agg({
    'salary':'sum','experience':'mean'
})

            salary  experience
department
HR          121000    4.500000
IT          117000    4.500000
sales       203000    4.666667

In [20]:
df9=df['dept_avg_salary']=df.groupby('department')['salary'].transform('mean')
print(df9)

0    60500.000000
1    67666.666667
2    58500.000000
3    67666.666667
4    58500.000000
5    60500.000000
6    67666.666667
Name: salary, dtype: float64

In [21]:
df1=df.groupby('department').filter(lambda x:len(x)>2)
print(df1)

  department employee  salary  experience  dept_avg_salary
1      sales        B   60000           4     67666.666667
3      sales        D   70000           5     67666.666667
6      sales        G   73000           5     67666.666667

In [29]:
df.pivot_table(
    values='salary',
    index='department',
    columns='employee',
    aggfunc='mean'

)

employee          A        B        C        D        E        F        G
department
HR          50000.0      NaN      NaN      NaN      NaN  71000.0      NaN
IT              NaN      NaN  45000.0      NaN  72000.0      NaN      NaN
sales           NaN  60000.0      NaN  70000.0      NaN      NaN  73000.0

In [32]:
df.pivot_table(
    values='experience',
    index='employee',
    columns='salary',
    aggfunc='mean'
)

salary    45000  50000  60000  70000  71000  72000  73000
employee
A           NaN    2.0    NaN    NaN    NaN    NaN    NaN
B           NaN    NaN    4.0    NaN    NaN    NaN    NaN
C           3.0    NaN    NaN    NaN    NaN    NaN    NaN
D           NaN    NaN    NaN    5.0    NaN    NaN    NaN
E           NaN    NaN    NaN    NaN    NaN    6.0    NaN
F           NaN    NaN    NaN    NaN    7.0    NaN    NaN
G           NaN    NaN    NaN    NaN    NaN    NaN    5.0