In [21]:
import pandas as pd
import numpy as np

df =pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, np.nan, 35, np.nan, 45],
    'City': ['New York', 'Paris', np.nan, 'London', 'Tokyo'],
    'Score': [85.5, 92.1, np.nan, 88.0, 76.5]
})
df.isna()

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False   True  False  False
4  False  False  False  False

In [22]:
df.isna().sum()

Name     0
Age      2
City     1
Score    1
dtype: int64

In [23]:
df.isnull()

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False   True  False  False
4  False  False  False  False

In [24]:
x=df.isna().sum().sum()
print(x)

4

In [25]:
df.dropna()

    Name   Age      City  Score
0  Alice  25.0  New York   85.5
4    Eve  45.0     Tokyo   76.5

In [29]:
df.dropna(axis=1)

      Name
0    Alice
1      Bob
2  Charlie
3    David
4      Eve

In [34]:
df.dropna(subset=['Name']df.dropna(thresh=3))

SyntaxError: invalid syntax. Perhaps you forgot a comma? (ipython-input-1292439526.py, line 1)

In [35]:
df.dropna(thresh=3)

    Name   Age      City  Score
0  Alice  25.0  New York   85.5
1    Bob   NaN     Paris   92.1
3  David   NaN    London   88.0
4    Eve  45.0     Tokyo   76.5

In [37]:
df.fillna(method='ffill')

/tmp/ipython-input-1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

      Name   Age      City  Score
0    Alice  25.0  New York   85.5
1      Bob  25.0     Paris   92.1
2  Charlie  35.0     Paris   92.1
3    David  35.0    London   88.0
4      Eve  45.0     Tokyo   76.5

In [38]:
df.fillna({'col1':0,'col2':'unknown'})

      Name   Age      City  Score
0    Alice  25.0  New York   85.5
1      Bob   NaN     Paris   92.1
2  Charlie  35.0       NaN    NaN
3    David   NaN    London   88.0
4      Eve  45.0     Tokyo   76.5

In [39]:
df.ffill()

      Name   Age      City  Score
0    Alice  25.0  New York   85.5
1      Bob  25.0     Paris   92.1
2  Charlie  35.0     Paris   92.1
3    David  35.0    London   88.0
4      Eve  45.0     Tokyo   76.5

In [40]:
df.bfill()

      Name   Age      City  Score
0    Alice  25.0  New York   85.5
1      Bob  35.0     Paris   92.1
2  Charlie  35.0    London   88.0
3    David  45.0    London   88.0
4      Eve  45.0     Tokyo   76.5

In [42]:
df.interpolate()

/tmp/ipython-input-4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

      Name   Age      City  Score
0    Alice  25.0  New York  85.50
1      Bob  30.0     Paris  92.10
2  Charlie  35.0       NaN  90.05
3    David  40.0    London  88.00
4      Eve  45.0     Tokyo  76.50

In [46]:
df.replace([30,35],[10,75])

      Name   Age      City  Score
0    Alice  25.0  New York   85.5
1      Bob   NaN     Paris   92.1
2  Charlie  75.0       NaN    NaN
3    David   NaN    London   88.0
4      Eve  45.0     Tokyo   76.5